import Mock from 'mockjs';
import qs from 'query-string';
import setupMock, { successResponseWrap } from '@/utils/setup-mock';
import { GetParams } from '@/types/global';

const { Random } = Mock;

// 部门模拟数据
const departmentData = Mock.mock({
  'list|22': [
    {
      'id|8': /[A-Z][a-z][-][0-9]/,
      'name|4-8': /[A-Z]/,
      'code|2-3': /[0-9]/,
      'createdTime': Random.datetime(),
      'note|8-12': /[A-Z]/,
    },
  ],
});

// 用户模拟数据
const userData = Mock.mock({
  'list|33': [
    {
      'id|8': /[A-Z][a-z][-][0-9]/,
      'username|4-8': /[A-Z]/,
      'department|2-3': /[0-9]/,
      'email|8-10': /[0-9]/,
      'phone|11': /[0-9]/,
      'accountStatus|1': Boolean,
      'createdTime': Random.datetime(),
      'note|8-12': /[A-Z]/,
    },
  ],
});

// 角色模拟数据
const roleData = Mock.mock({
  'list|33': [
    {
      'id|8': /[A-Z][a-z][-][0-9]/,
      'roleName|4-8': /[A-Z]/,
      'roleCode|2-3': /[0-9]/,
      'createdTime': Random.datetime(),
      'note|8-12': /[A-Z]/,
    },
  ],
});

setupMock({
  setup() {
    Mock.mock(new RegExp('/api/system/department'), (params: GetParams) => {
      const { current = 1, pageSize = 10 } = qs.parseUrl(params.url).query;
      const p = current as number;
      const ps = pageSize as number;
      return successResponseWrap({
        list: departmentData.list.slice((p - 1) * ps, p * ps),
        total: 22,
      });
    });

    Mock.mock(new RegExp('/api/system/user'), (params: GetParams) => {
      const { current = 1, pageSize = 10 } = qs.parseUrl(params.url).query;
      const p = current as number;
      const ps = pageSize as number;
      return successResponseWrap({
        list: userData.list.slice((p - 1) * ps, p * ps),
        total: 33,
      });
    });

    Mock.mock(new RegExp('/api/system/role'), (params: GetParams) => {
      const { current = 1, pageSize = 10 } = qs.parseUrl(params.url).query;
      const p = current as number;
      const ps = pageSize as number;
      return successResponseWrap({
        list: roleData.list.slice((p - 1) * ps, p * ps),
        total: 33,
      });
    });

    Mock.mock(new RegExp('/dev-api/system/menu/list'), (params: GetParams) => {
      const { current = 1, pageSize = 10 } = qs.parseUrl(params.url).query;
      const p = current as number;
      const ps = pageSize as number;
      return successResponseWrap({
        list: [
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1,
            menuName: '系统管理',
            parentName: null,
            parentId: 0,
            orderNum: '1',
            path: 'system',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '0',
            status: '0',
            perms: '',
            icon: 'system',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2,
            menuName: '系统监控',
            parentName: null,
            parentId: 0,
            orderNum: '2',
            path: 'monitor',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '0',
            status: '0',
            perms: '',
            icon: 'monitor',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 3,
            menuName: '系统工具',
            parentName: null,
            parentId: 0,
            orderNum: '3',
            path: 'tool',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '0',
            status: '0',
            perms: '',
            icon: 'tool',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-09-13 21:58:54',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 5,
            menuName: '流程菜单',
            parentName: null,
            parentId: 0,
            orderNum: '4',
            path: 'activiti',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '0',
            status: '0',
            perms: 'activiti:modeler:list',
            icon: 'cascader',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-11-10 22:13:34',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2008,
            menuName: '我的OA',
            parentName: null,
            parentId: 0,
            orderNum: '5',
            path: 'OA',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '1',
            status: '0',
            perms: '',
            icon: 'guide',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-11-04 10:53:24',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2006,
            menuName: '待办任务',
            parentName: null,
            parentId: 0,
            orderNum: '6',
            path: 'task',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '1',
            status: '0',
            perms: '',
            icon: 'excel',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-11-10 22:17:36',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2009,
            menuName: '历史流程',
            parentName: null,
            parentId: 0,
            orderNum: '7',
            path: 'open',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '1',
            status: '0',
            perms: '',
            icon: 'eye-open',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-11 17:49:39',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2013,
            menuName: '工单管理',
            parentName: null,
            parentId: 0,
            orderNum: '8',
            path: 'order',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '0',
            status: '0',
            perms: '',
            icon: 'job',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-11 17:59:28',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2017,
            menuName: '统计分析',
            parentName: null,
            parentId: 0,
            orderNum: '9',
            path: 'report',
            component: 'report/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'report:1:list',
            icon: 'chart',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-18 09:25:47',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2020,
            menuName: '政策规定',
            parentName: null,
            parentId: 0,
            orderNum: '10',
            path: 'policy',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '0',
            status: '0',
            perms: '',
            icon: 'education',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 100,
            menuName: '用户管理',
            parentName: null,
            parentId: 1,
            orderNum: '1',
            path: 'user',
            component: 'system/user/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'system:user:list',
            icon: 'user',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 101,
            menuName: '角色管理',
            parentName: null,
            parentId: 1,
            orderNum: '2',
            path: 'role',
            component: 'system/role/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'system:role:list',
            icon: 'peoples',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 103,
            menuName: '部门管理',
            parentName: null,
            parentId: 1,
            orderNum: '3',
            path: 'dept',
            component: 'system/dept/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'system:dept:list',
            icon: 'tree',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 102,
            menuName: '菜单管理',
            parentName: null,
            parentId: 1,
            orderNum: '4',
            path: 'menu',
            component: 'system/menu/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'system:menu:list',
            icon: 'tree-table',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 104,
            menuName: '岗位管理',
            parentName: null,
            parentId: 1,
            orderNum: '5',
            path: 'post',
            component: 'system/post/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'system:post:list',
            icon: 'post',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 105,
            menuName: '字典管理',
            parentName: null,
            parentId: 1,
            orderNum: '6',
            path: 'dict',
            component: 'system/dict/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'system:dict:list',
            icon: 'dict',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 106,
            menuName: '参数设置',
            parentName: null,
            parentId: 1,
            orderNum: '7',
            path: 'config',
            component: 'system/config/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'system:config:list',
            icon: 'edit',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 107,
            menuName: '通知公告',
            parentName: null,
            parentId: 1,
            orderNum: '8',
            path: 'notice',
            component: 'system/notice/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'system:notice:list',
            icon: 'message',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-24 14:55:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2023,
            menuName: '事件类别',
            parentName: null,
            parentId: 1,
            orderNum: '9',
            path: 'event',
            component: 'system/event/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'system:event:list',
            icon: 'build',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 108,
            menuName: '日志管理',
            parentName: null,
            parentId: 1,
            orderNum: '10',
            path: 'log',
            component: 'system/log/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'M',
            visible: '0',
            status: '0',
            perms: '',
            icon: 'log',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 109,
            menuName: '在线用户',
            parentName: null,
            parentId: 2,
            orderNum: '1',
            path: 'online',
            component: 'monitor/online/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'monitor:online:list',
            icon: 'online',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 110,
            menuName: '定时任务',
            parentName: null,
            parentId: 2,
            orderNum: '2',
            path: 'job',
            component: 'monitor/job/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'monitor:job:list',
            icon: 'job',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 111,
            menuName: '数据监控',
            parentName: null,
            parentId: 2,
            orderNum: '3',
            path: 'druid',
            component: 'monitor/druid/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'monitor:druid:list',
            icon: 'druid',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 112,
            menuName: '服务监控',
            parentName: null,
            parentId: 2,
            orderNum: '4',
            path: 'server',
            component: 'monitor/server/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'monitor:server:list',
            icon: 'server',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 113,
            menuName: '表单构建',
            parentName: null,
            parentId: 3,
            orderNum: '1',
            path: 'build',
            component: 'tool/build/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'tool:build:list',
            icon: 'build',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 114,
            menuName: '代码生成',
            parentName: null,
            parentId: 3,
            orderNum: '2',
            path: 'gen',
            component: 'tool/gen/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'tool:gen:list',
            icon: 'code',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 115,
            menuName: '系统接口',
            parentName: null,
            parentId: 3,
            orderNum: '3',
            path: 'swagger',
            component: 'tool/swagger/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'tool:swagger:list',
            icon: 'swagger',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-09-14 23:09:31',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1901,
            menuName: '流程定义',
            parentName: null,
            parentId: 5,
            orderNum: '1',
            path: 'definition',
            component: 'activiti/definition/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'activiti:modeler',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1001,
            menuName: '用户查询',
            parentName: null,
            parentId: 100,
            orderNum: '1',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1002,
            menuName: '用户新增',
            parentName: null,
            parentId: 100,
            orderNum: '2',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1003,
            menuName: '用户修改',
            parentName: null,
            parentId: 100,
            orderNum: '3',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1004,
            menuName: '用户删除',
            parentName: null,
            parentId: 100,
            orderNum: '4',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1005,
            menuName: '用户导出',
            parentName: null,
            parentId: 100,
            orderNum: '5',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1006,
            menuName: '用户导入',
            parentName: null,
            parentId: 100,
            orderNum: '6',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:import',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1007,
            menuName: '重置密码',
            parentName: null,
            parentId: 100,
            orderNum: '7',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:resetPwd',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1008,
            menuName: '角色查询',
            parentName: null,
            parentId: 101,
            orderNum: '1',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:role:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1009,
            menuName: '角色新增',
            parentName: null,
            parentId: 101,
            orderNum: '2',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:role:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1010,
            menuName: '角色修改',
            parentName: null,
            parentId: 101,
            orderNum: '3',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:role:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1011,
            menuName: '角色删除',
            parentName: null,
            parentId: 101,
            orderNum: '4',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:role:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1012,
            menuName: '角色导出',
            parentName: null,
            parentId: 101,
            orderNum: '5',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:role:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1013,
            menuName: '菜单查询',
            parentName: null,
            parentId: 102,
            orderNum: '1',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:menu:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1014,
            menuName: '菜单新增',
            parentName: null,
            parentId: 102,
            orderNum: '2',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:menu:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1015,
            menuName: '菜单修改',
            parentName: null,
            parentId: 102,
            orderNum: '3',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:menu:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1016,
            menuName: '菜单删除',
            parentName: null,
            parentId: 102,
            orderNum: '4',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:menu:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1017,
            menuName: '部门查询',
            parentName: null,
            parentId: 103,
            orderNum: '1',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:dept:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1018,
            menuName: '部门新增',
            parentName: null,
            parentId: 103,
            orderNum: '2',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:dept:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1019,
            menuName: '部门修改',
            parentName: null,
            parentId: 103,
            orderNum: '3',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:dept:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1020,
            menuName: '部门删除',
            parentName: null,
            parentId: 103,
            orderNum: '4',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:dept:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1021,
            menuName: '岗位查询',
            parentName: null,
            parentId: 104,
            orderNum: '1',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:post:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1022,
            menuName: '岗位新增',
            parentName: null,
            parentId: 104,
            orderNum: '2',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:post:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1023,
            menuName: '岗位修改',
            parentName: null,
            parentId: 104,
            orderNum: '3',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:post:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1024,
            menuName: '岗位删除',
            parentName: null,
            parentId: 104,
            orderNum: '4',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:post:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1025,
            menuName: '岗位导出',
            parentName: null,
            parentId: 104,
            orderNum: '5',
            path: '',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:post:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1026,
            menuName: '字典查询',
            parentName: null,
            parentId: 105,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:dict:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1027,
            menuName: '字典新增',
            parentName: null,
            parentId: 105,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:dict:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1028,
            menuName: '字典修改',
            parentName: null,
            parentId: 105,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:dict:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1029,
            menuName: '字典删除',
            parentName: null,
            parentId: 105,
            orderNum: '4',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:dict:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1030,
            menuName: '字典导出',
            parentName: null,
            parentId: 105,
            orderNum: '5',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:dict:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1031,
            menuName: '参数查询',
            parentName: null,
            parentId: 106,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:config:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1032,
            menuName: '参数新增',
            parentName: null,
            parentId: 106,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:config:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1033,
            menuName: '参数修改',
            parentName: null,
            parentId: 106,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:config:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1034,
            menuName: '参数删除',
            parentName: null,
            parentId: 106,
            orderNum: '4',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:config:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1035,
            menuName: '参数导出',
            parentName: null,
            parentId: 106,
            orderNum: '5',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:config:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1036,
            menuName: '公告查询',
            parentName: null,
            parentId: 107,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:notice:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1037,
            menuName: '公告新增',
            parentName: null,
            parentId: 107,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:notice:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1038,
            menuName: '公告修改',
            parentName: null,
            parentId: 107,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:notice:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1039,
            menuName: '公告删除',
            parentName: null,
            parentId: 107,
            orderNum: '4',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:notice:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 500,
            menuName: '操作日志',
            parentName: null,
            parentId: 108,
            orderNum: '1',
            path: 'operlog',
            component: 'monitor/operlog/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'monitor:operlog:list',
            icon: 'form',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 501,
            menuName: '登录日志',
            parentName: null,
            parentId: 108,
            orderNum: '2',
            path: 'logininfor',
            component: 'monitor/logininfor/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'monitor:logininfor:list',
            icon: 'logininfor',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1046,
            menuName: '在线查询',
            parentName: null,
            parentId: 109,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:online:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1047,
            menuName: '批量强退',
            parentName: null,
            parentId: 109,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:online:batchLogout',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1048,
            menuName: '单条强退',
            parentName: null,
            parentId: 109,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:online:forceLogout',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1049,
            menuName: '任务查询',
            parentName: null,
            parentId: 110,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:job:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1050,
            menuName: '任务新增',
            parentName: null,
            parentId: 110,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:job:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1051,
            menuName: '任务修改',
            parentName: null,
            parentId: 110,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:job:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1052,
            menuName: '任务删除',
            parentName: null,
            parentId: 110,
            orderNum: '4',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:job:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1053,
            menuName: '状态修改',
            parentName: null,
            parentId: 110,
            orderNum: '5',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:job:changeStatus',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1054,
            menuName: '任务导出',
            parentName: null,
            parentId: 110,
            orderNum: '7',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:job:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1055,
            menuName: '生成查询',
            parentName: null,
            parentId: 114,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'tool:gen:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1056,
            menuName: '生成修改',
            parentName: null,
            parentId: 114,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'tool:gen:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1058,
            menuName: '导入代码',
            parentName: null,
            parentId: 114,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'tool:gen:import',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1057,
            menuName: '生成删除',
            parentName: null,
            parentId: 114,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'tool:gen:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1059,
            menuName: '预览代码',
            parentName: null,
            parentId: 114,
            orderNum: '4',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'tool:gen:preview',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1060,
            menuName: '生成代码',
            parentName: null,
            parentId: 114,
            orderNum: '5',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'tool:gen:code',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1040,
            menuName: '操作查询',
            parentName: null,
            parentId: 500,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:operlog:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1041,
            menuName: '操作删除',
            parentName: null,
            parentId: 500,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:operlog:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1042,
            menuName: '日志导出',
            parentName: null,
            parentId: 500,
            orderNum: '4',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:operlog:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1043,
            menuName: '登录查询',
            parentName: null,
            parentId: 501,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:logininfor:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1044,
            menuName: '登录删除',
            parentName: null,
            parentId: 501,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:logininfor:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-22 14:27:04',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1045,
            menuName: '日志导出',
            parentName: null,
            parentId: 501,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'monitor:logininfor:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-28 22:30:57',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2001,
            menuName: '请假查询',
            parentName: null,
            parentId: 2000,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'workflow:leave:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-28 22:30:57',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2002,
            menuName: '请假新增',
            parentName: null,
            parentId: 2000,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'workflow:leave:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-28 22:30:57',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2003,
            menuName: '请假修改',
            parentName: null,
            parentId: 2000,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'workflow:leave:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-28 22:30:57',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2004,
            menuName: '请假删除',
            parentName: null,
            parentId: 2000,
            orderNum: '4',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'workflow:leave:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-28 22:30:57',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2005,
            menuName: '请假导出',
            parentName: null,
            parentId: 2000,
            orderNum: '5',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'workflow:leave:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-11-04 10:54:28',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2007,
            menuName: '代办任务',
            parentName: null,
            parentId: 2006,
            orderNum: '1',
            path: 'task',
            component: 'activiti/task',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: '',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-28 22:30:57',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2000,
            menuName: '请假',
            parentName: null,
            parentId: 2008,
            orderNum: '1',
            path: 'leave',
            component: 'workflow/leave/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'workflow:leave:list',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2020-10-28 22:30:57',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2010,
            menuName: '请假历史',
            parentName: null,
            parentId: 2009,
            orderNum: '1',
            path: 'leaveAll',
            component: 'workflow/leave/leaveAll',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'workflow:leave:list',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-09-08 10:12:52',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2030,
            menuName: '修改历史表单',
            parentName: null,
            parentId: 2009,
            orderNum: '1',
            path: '',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'task:form:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-11 17:54:25',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2014,
            menuName: '待办任务',
            parentName: null,
            parentId: 2013,
            orderNum: '1',
            path: 'current',
            component: 'order/current/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: '',
            icon: 'upload',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-11 14:51:11',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2045,
            menuName: '督办',
            parentName: null,
            parentId: 2013,
            orderNum: '1',
            path: '',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'order:order:supervise',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-09-16 14:31:43',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2032,
            menuName: '进行中工单',
            parentName: null,
            parentId: 2013,
            orderNum: '2',
            path: 'going',
            component: 'order/going/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: '',
            icon: 'guide',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-11 17:56:35',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2015,
            menuName: '历史工单',
            parentName: null,
            parentId: 2013,
            orderNum: '3',
            path: 'history',
            component: 'order/history/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'order:order:list',
            icon: 'form',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-09-21 13:51:35',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2033,
            menuName: '工单详情',
            parentName: null,
            parentId: 2013,
            orderNum: '4',
            path: 'detail',
            component: 'order/detail/index',
            isFrame: '1',
            isCache: '1',
            menuType: 'C',
            visible: '1',
            status: '0',
            perms: '',
            icon: 'build',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-21 14:03:32',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2048,
            menuName: '历史工单详情',
            parentName: null,
            parentId: 2013,
            orderNum: '5',
            path: 'hisDetail',
            component: 'order/hisDetail/index',
            isFrame: '1',
            isCache: '1',
            menuType: 'C',
            visible: '1',
            status: '0',
            perms: '',
            icon: 'bug',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-12 16:29:29',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2047,
            menuName: '修改历史表单',
            parentName: null,
            parentId: 2013,
            orderNum: '6',
            path: '',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'task:form:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-09-21 15:42:47',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2034,
            menuName: '导入',
            parentName: null,
            parentId: 2014,
            orderNum: '1',
            path: '',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'order:order:import',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-10 15:12:13',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2043,
            menuName: '新增',
            parentName: null,
            parentId: 2014,
            orderNum: '2',
            path: '',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'order:order:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-10 15:12:34',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2044,
            menuName: '删除',
            parentName: null,
            parentId: 2014,
            orderNum: '3',
            path: '',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'order:order:delete',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-11 15:31:28',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2046,
            menuName: '修改',
            parentName: null,
            parentId: 2014,
            orderNum: '4',
            path: '',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'order:order:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-10 10:15:03',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2041,
            menuName: '导出',
            parentName: null,
            parentId: 2015,
            orderNum: '1',
            path: '',
            component: null,
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'order:order:export',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-18 09:27:36',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2021,
            menuName: '区',
            parentName: null,
            parentId: 2020,
            orderNum: '1',
            path: 'area',
            component: 'policy/area/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'policy:file:AreaFileList',
            icon: 'documentation',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-09-27 16:11:19',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2036,
            menuName: '图片查询',
            parentName: null,
            parentId: 2020,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:upload:query',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-18 09:31:07',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2022,
            menuName: '镇',
            parentName: null,
            parentId: 2020,
            orderNum: '2',
            path: 'town',
            component: 'policy/town/index',
            isFrame: '1',
            isCache: '0',
            menuType: 'C',
            visible: '0',
            status: '0',
            perms: 'policy/file/index',
            icon: 'clipboard',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-09-27 16:11:19',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2037,
            menuName: '图片新增',
            parentName: null,
            parentId: 2020,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:upload:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-09-27 16:11:19',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2038,
            menuName: '图片修改',
            parentName: null,
            parentId: 2020,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:upload:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-09-27 16:11:19',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2039,
            menuName: '图片删除',
            parentName: null,
            parentId: 2020,
            orderNum: '4',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:upload:remove',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-24 19:16:50',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2024,
            menuName: '事件类型查询',
            parentName: null,
            parentId: 2023,
            orderNum: '1',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:eventType:list',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-24 19:16:50',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2025,
            menuName: '事件类型新增',
            parentName: null,
            parentId: 2023,
            orderNum: '2',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:eventType:add',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-24 19:16:50',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2026,
            menuName: '事件类型修改',
            parentName: null,
            parentId: 2023,
            orderNum: '3',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:eventType:edit',
            icon: '#',
            children: [],
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-08-24 19:16:50',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 2027,
            menuName: '事件类型删除',
            parentName: null,
            parentId: 2023,
            orderNum: '4',
            path: '#',
            component: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:eventType:remove',
            icon: '#',
            children: [],
          },
        ],
      });
    });
  },
});
